### ISSUE TITLE
Is it possible to change the font color?

### ISSUE THREAD

**Issue by RyanTG** [MarianArlt/kde-plasmoid-chiliclock#7]
Is it possible to change the font color?

Is the color inherited from a system color (and if so, do you know which one)? Or could I edit it myself?

Thanks! Great job - I love this clock.

**Comment by MarianArlt** [comment]
The color of the rendered objects is taken by design from the current KDE color scheme selected from "System Settings -> Colors". In specific the color of "Window Text". Apparently changing this color to something different will change your whole desktop appearance.

If you want to hard code a different color for your clock you can change `~/.local/share/plasma/plasmoids/org.kde.plasma.chiliclock/contents/ui/DigitalClock.qml` and [add a color attribute](https://doc.qt.io/qt-5/qml-qtquick-text.html#color-prop) to the `dateLabel` and `timeLabel` components.

Hope that helps.

**Comment by RyanTG** [comment]
Thank you! Very very helpful.
